### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by solanoon** [QizhiPei/SMT-DTA#1]
Hello QizhiPei,

I want to run your model as a baseline model but facing several problems when trying to generate data.

1. The Pfam link you provided in the readme file is unavailable and
2. You have mentioned that BindingDB data is supposed to be downloaded in tsv format, but the link you provided only contains sdf file in version 2018.
3. Thus, I wonder whether could you share the data used in your experiments for reproduction?

Thank you for your time!

**Comment by QizhiPei** [comment]
Thank you for your interest in our work.

For the Pfam ftp file link in the[ README](https://github.com/QizhiPei/SMT-DTA/blob/main/README.md), it is always changing and I have updated it to the newest version. The protein fasta of Pfam and compound SMILES of PubChem are mainly used for anxiliary MLM task. So you can randomly sample 10M data(or more for probably better result) to reproduce our experiments.
For the BindingDB v2018, we used the same data as [DeepAffinity](https://academic.oup.com/bioinformatics/article/35/18/3329/5320555?login=false) for fair comparison. But the [Google Drive link](https://github.com/Shen-Lab/DeepAffinity/tree/master/data/script/split_data_script) provided in its resporistry is a sdf file, not a tsv file. So we directly use the [IC50.tar.xz, Ki.tar.xz](https://github.com/Shen-Lab/DeepAffinity/tree/master/data/dataset) data processed by DeepAffinity in our experiments.

Thanks

**Comment by QizhiPei** [comment]
Hello, solanoon

@solanoon We have uploaded the data and trained SMT-DTA model. Please refer to our newest README and repository for more information. You can use them to reproduce our experiments or directly run evaluation.

Thanks
Qizhi
