### ISSUE TITLE
single gpu run

### ISSUE THREAD

**Issue by pcardenasg** [QizhiPei/SMT-DTA#10]
Hi! I'd like to debug through your model to explore your proposal further, but from what I understand (and after trying to do so), fairseq doesn't allow working with breakpoints to stop the code mid run. Do you have any command suggestions for debugging? In addition, I have computational restraints and would like to know if there is any modification I can do to the training command so that it trains in only one gpu (or at least not occupy all the gpus in my device). Thanks.

**Comment by QizhiPei** [comment]
Hi!
To my knowledge, you can add the breakpoint into the fairseq code, and the code should stop at that point.
If you want to specify the GPUs, you can firstly set the environment variable CUDA_VISIBLE_DEVICES before runing python script.
