### ISSUE TITLE
About the device and training time

### ISSUE THREAD

**Issue by ShipengWang** [QizhiPei/SMT-DTA#2]
Hello,

This is an interesting work!

Could you please tell me the GPU you used and how long the training spend?

Thanks

**Comment by QizhiPei** [comment]
Thank you for your interest in our work.

We use 8xV100 32GB GPU for training.

The training time varies with the size of the dataset, ranging from about 1 day(on DAVIS dataset) to about 8 days(on BindingDB IC50 dataset). 

Thanks!
