### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by raghavchandra123** [QizhiPei/SMT-DTA#3]
Hello,

Congratulations on the interesting work! Would you be willing to share the trained models? (e.g. for bindingdb IC50).

Thanks, Raghav

**Comment by QizhiPei** [comment]
Hello, Raghav

@raghavchandra123 We have uploaded the data and trained SMT-DTA model. Please refer to our newest README and repository for more information.

Thanks
Qizhi

**Comment by raghavchandra123** [comment]
Hello Qizhi,

Thank you so much for the prompt response and for the trained model!

Thanks, Raghav
