### ISSUE TITLE
About the train.py

### ISSUE THREAD

**Issue by Ivan-Tang-3D** [QizhiPei/SMT-DTA#6]
Hi Zhipei,

It is a very nice study! I am just a bit confused about the train.py you used for DTI task. In the homepage command lines, It mentions train.py, but I did not find it. Could you tel me where it is, please. Or which script you used to train the original model.
Thanks

**Comment by Ivan-Tang-3D** [comment]
https://github.com/facebookresearch/fairseq/blob/main/fairseq_cli/train.py Is this link?

**Comment by QizhiPei** [comment]
> https://github.com/facebookresearch/fairseq/blob/main/fairseq_cli/train.py Is this link?

Yes. 
In the README, there are some commands used for download and merge the fairseq framwork, in which the `train.py` will be downloaded.

``` bash
git clone https://github.com/QizhiPei/SMT-DTA.git
cd SMT-DTA
pwd=$PWD

git clone git@github.com:pytorch/fairseq.git /tmp/fairseq
cd /tmp/fairseq
git checkout v0.10.2

cd $pwd
cp -r -n /tmp/fairseq/* ./
```
Note that you need to switch to the verson `v0.10.2` of fairseq using the above `git checkout v0.10.2` command.
Hope this can help you!
