### ISSUE TITLE
I have some question about dealing with the protein sequence!

### ISSUE THREAD

**Issue by BBaekdabang** [QizhiPei/SMT-DTA#7]
I'm the beginner of this domain.
I know that there are some protein sequences have long length.
How did you deal with that long protein sequences?
I know that the language model kind of bert have the limit of input token length.

**Comment by QizhiPei** [comment]
Hi

Thanks for your interest in our work. Currently, we deal with this problem by truncating protein sequences that exceed a length of 1024 to 1024.

**Comment by AmT42** [comment]
What happens if you truncate the pocket ? are you taking care of that on the trucating ?

**Comment by QizhiPei** [comment]
Hi,

We do not take care of the pocket during truncation. We mainly consider the mean and max length of the input molecule and protein, as well as the size of GPU memory.
