### ISSUE TITLE
A simple case directly using the trained model for inference is NEEDED!

### ISSUE THREAD

**Issue by TernencezzZ** [QizhiPei/SMT-DTA#8]
Hi, thanks for this interesting job!!

Could you kindly provide a quick start case for inference between drugs and targets? It would be great to include the following:

1. Example input drug files
2. Example input target files
3. Input for parameters --data-bin and --test-data

I want to test your trained model on my custom drugs and target proteins. As a beginner in DTI learning, having a simple case would help me less confused. Thank you very much!

**Comment by QizhiPei** [comment]
Thanks for your suggesion~
I have update the README , examples, and scripts accordingly. Please kindly check the corresponding [section](https://github.com/QizhiPei/SSM-DTA?tab=readme-ov-file#inference-on-your-own-drug-target-pairs).
