### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mmagithub** [QizhiPei/SMT-DTA#9]
Hi,

I am trying to install the repository locally, but trying to follow the instructions, it seems that there is no setup.py 

Thanks
M

**Comment by QizhiPei** [comment]
Hi,
The setup.py should be in the fairseq repository. The commands
```shell
git clone git@github.com:pytorch/fairseq.git /tmp/fairseq
cd /tmp/fairseq
git checkout v0.10.2

cd $pwd
cp -r -n /tmp/fairseq/* ./
``` 
in the instruction will download fairseq and copy it into the SSM-DTA folder.

Thanks
Qizhi Pei
